/** Search actions */
export const TERM_CHANGE = 'TERM_CHANGE';
export const DESTINATION_CHANGE = 'DESTINATION_CHANGE';

export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';

export const SET_VERSION = 'SET_VERSION';

export const POST_SEARCH_REQUEST = 'POST_SEARCH_REQUEST';
export const POST_SEARCH_SUCCESS = 'POST_SEARCH_SUCCESS';
export const POST_SEARCH_FAILURE = 'POST_SEARCH_FAILURE';

export const SMART_SEARCH_REQUEST = 'SMART_SEARCH_REQUEST';
export const SMART_SEARCH_SUCCESS = 'SMART_SEARCH_SUCCESS';
export const SMART_SEARCH_FAILURE = 'SMART_SEARCH_FAILURE';

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';
export const USER_LOCATION_FAILURE = 'USER_LOCATION_FAILURE';

export const LOCATION_AUTOCOMPLETE_REQUEST = 'LOCATION_AUTOCOMPLETE_REQUEST';
export const LOCATION_AUTOCOMPLETE_SUCCESS = 'LOCATION_AUTOCOMPLETE_SUCCESS';
export const LOCATION_AUTOCOMPLETE_FAILURE = 'LOCATION_AUTOCOMPLETE_FAILURE';
export const TOGGLE_LOCATION = 'TOGGLE_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';

/** Results actions */
export const SELECT_ITEM_REQUEST = 'SELECT_ITEM_REQUEST';
export const SELECT_ITEM_SUCCESS = 'SELECT_ITEM_SUCCESS';
export const SELECT_ITEM_FAILURE = 'SELECT_ITEM_FAILURE';

/** Product actions */
export const TOGGLE_IMAGES = 'TOGGLE_IMAGES';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const SET_RATING = 'SET_RATING';
export const SET_COMMENT = 'SET_COMMENT';
export const SET_EMAIL = 'SET_EMAIL';

export const SET_CHOSEN_PRODUCT_REQUEST = 'SET_CHOSEN_PRODUCT_REQUEST';
export const SET_CHOSEN_PRODUCT_SUCCESS = 'SET_CHOSEN_PRODUCT_SUCCESS';
export const SET_CHOSEN_PRODUCT_FAILURE = 'SET_CHOSEN_PRODUCT_FAILURE';

export const POST_FEEDBACK_REQUEST = 'POST_FEEDBACK_REQUEST';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';
export const POST_FEEDBACK_FAILURE = 'POST_FEEDBACK_FAILURE';
