/** Accounts actions */
export const SHOW_ADD = 'SHOW_ADD';
export const HIDE_ADD = 'HIDE_ADD';

export const SHOW_IMPORT = 'SHOW_IMPORT';
export const HIDE_IMPORT = 'HIDE_IMPORT';

export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';

export const POST_ACCOUNT_REQUEST = 'POST_ACCOUNT_REQUEST';
export const POST_ACCOUNT_SUCCESS = 'POST_ACCOUNT_SUCCESS';
export const POST_ACCOUNT_FAILURE = 'POST_ACCOUNT_FAILURE';


/** Transactions actions */
export const GET_ACCOUNT_TRX_REQUEST = 'GET_ACCOUNT_TRX_REQUEST';
export const GET_ACCOUNT_TRX_SUCCESS = 'GET_ACCOUNT_TRX_SUCCESS';
export const GET_ACCOUNT_TRX_FAILURE = 'GET_ACCOUNT_TRX_FAILURE';

export const POST_TRXFILE_REQUEST = 'POST_TRXFILE_REQUEST';
export const POST_TRXFILE_SUCCESS = 'POST_TRXFILE_SUCCESS';
export const POST_TRXFILE_FAILURE = 'POST_TRXFILE_FAILURE';


/** Dashboard actions */
export const SELECT_CURRENCY = 'SELECT_CURRENCY';

export const GET_ACCOUNTS_SUMMARY_REQUEST = 'GET_ACCOUNTS_SUMMARY_REQUEST';
export const GET_ACCOUNTS_SUMMARY_SUCCESS = 'GET_ACCOUNTS_SUMMARY_SUCCESS';
export const GET_ACCOUNTS_SUMMARY_FAILURE = 'GET_ACCOUNTS_SUMMARY_FAILURE';

export const GET_KPIS_REQUEST = 'GET_KPIS_REQUEST';
export const GET_KPIS_SUCCESS = 'GET_KPIS_SUCCESS';
export const GET_KPIS_FAILURE = 'GET_KPIS_FAILURE';

export const GET_TIMESTAMP_REQUEST = 'GET_TIMESTAMP_REQUEST';
export const GET_TIMESTAMP_SUCCESS = 'GET_TIMESTAMP_SUCCESS';
export const GET_TIMESTAMP_FAILURE = 'GET_TIMESTAMP_FAILURE';
